### PR TITLE
Fully initialize the extension in `Bundle::createContainerExtension()` for compatibility with Symfony 7.4

### LINKED ISSUE #197: [Bug][Symfony 7.4]: SensiolabsGotenbergExtension::$builderStack must not be accessed before initialization
### Reproducer

_No response_

### Description

This bundle doesn't work with Symfony 7.4.0-BETA2.

See https://github.com/symfony/symfony/issues/62275

### Gotenberg Version

n/a

### Gotenberg Bundle Version

1.0.0

### PR DESCRIPTION
**Pull request by GromNaN**
| Q                       | A        |
|-------------------------|----------|
| Gotenberg API version ? | 8.x      |
| Bug fix ?               | yes      |
| New feature ?           | no       |
| BC break ?              | yes      |
| Issues                  | Fix #197 |

## Description

In order to generate array shapes for all environments, Symfony FrameworkBundle needs to get the configuration of all the bundles without initializing the container.

The extension must be fully initialized in `Bundle::createContainerExtension()`.

### CODE REVIEW

File: src/DependencyInjection/SensiolabsGotenbergExtension.php [hunk 1]
```diff
@@ -55,6 +60,17 @@ public function registerBuilder(string $class): void
...
+    /**
+     * @param class-string<BuilderInterface> $class
+     */
+    public function getBuilder(string $class): string
+    {
+        return $this->builderStack->getBuilders()[$class] ?? throw new \InvalidArgumentException(\sprintf('The builder "%s" is not registered.', $class));
+    }
+
+    /**
+     * @deprecated The builder pack is created by the extension itself
```
Comment (GromNaN) [inline src/DependencyInjection/SensiolabsGotenbergExtension.php]:
```suggestion
     * @deprecated The BuilderSack is created by the extension itself
```

File: src/DependencyInjection/SensiolabsGotenbergExtension.php [hunk 2]
```diff
@@ -55,6 +60,17 @@ public function registerBuilder(string $class): void
...
+    /**
+     * @param class-string<BuilderInterface> $class
+     */
+    public function getBuilder(string $class): string
+    {
+        return $this->builderStack->getBuilders()[$class] ?? throw new \InvalidArgumentException(\sprintf('The builder "%s" is not registered.', $class));
+    }
+
+    /**
+     * @deprecated The BuilderSack is created by the extension itself
```
Comment (Jean-Beru) [inline src/DependencyInjection/SensiolabsGotenbergExtension.php]:
```suggestion
     * @deprecated The BuilderStack is created by the extension itself
```

File: src/DependencyInjection/CompilerPass/GotenbergPass.php [hunk 3]
```diff
@@ -29,7 +26,7 @@ public function process(ContainerBuilder $container): void
 
             /** @var string $class */
```
Comment (Jean-Beru) [inline src/DependencyInjection/CompilerPass/GotenbergPass.php]: Should be `class-string<BuilderInterface>` to make phpstan happy.

**Review by Jean-Beru — COMMENTED** [review]
Thanks for this contribution !

I ran GitHub CI and it seems that `SensiolabsGotenbergExtensionTest` should be updated too.

File: tests/DependencyInjection/SensiolabsGotenbergExtensionTest.php [hunk 4]
```diff
@@ -53,8 +50,6 @@ private function getExtension(): SensiolabsGotenbergExtension
         $extension->registerBuilder(MarkdownScreenshotBuilder::class);
         $extension->registerBuilder(UrlScreenshotBuilder::class);
 
-        $this->getContainerBuilder()->addCompilerPass(new GotenbergPass($builderStack));
```
Comment (GromNaN) [inline tests/DependencyInjection/SensiolabsGotenbergExtensionTest.php:56]: This is not necessary for this test.

**Review by Jean-Beru — APPROVED** [review]

**Review by Neirda24 — APPROVED** [review]
awesome thank you for this contribution @GromNaN . I wonder though why our tests were working @Jean-Beru  (didn't had time to check yet) for symfony 7.4 / 8.0. It shouldn't have worked.

**Comment by Jean-Beru** [comment]
> I wonder though why our tests were working @Jean-Beru (didn't had time to check yet) for symfony 7.4 / 8.0. It shouldn't have worked.

It might be due to latest merged PRs in 7.4 (ex: https://github.com/symfony/symfony/pull/62129).

**Comment by Jean-Beru** [comment]
Thanks @GromNaN ! 

Very great improvement indeed :tada: 
image
