### PR TITLE
fix: use valid type for webhook configuration example

### LINKED ISSUE #142: ConfigBuilder warning - Array to string conversion
### Reproducer

bin/console cache:clear

### Description

On clearing cache I get a warning:
`Failed to generate ConfigBuilder for extension Sensiolabs\GotenbergBundle\DependencyInjection\SensiolabsGotenbergExtension: Warning: Array to string conversion`
I only noticed when building in production where warnings are elevated.

The warning seems to come from the example route provided in `Configuration::addWebhookConfigurationNode()`:
`->example([
                        'https://webhook.site/#!/view/{some-token}',
                        ['my_route', ['param1' => 'value1', 'param2' => 'value2']],
                    ])`

This triggers a warning in Symfony's `ConfigBuilderGenerator::getComment()`:

`if (!$node instanceof ArrayNode) {
            foreach ((array) ($node->getExample() ?? []) as $example) {
                $comment .= ' * @example '.$example."\n";
            }`

Is the entire example node meant to be wrapped in quotation marks?

### Gotenberg Version

8.15.3

### Gotenberg Bundle Version

0.3.0

### PR DESCRIPTION
**Pull request by Jean-Beru**
| Q                       | A        |
|-------------------------|----------|
| Gotenberg API version ? |       |
| Bug fix ?               | yes  |
| New feature ?           | no   |
| BC break ?              | no   |
| Issues                  | Fix #142  |

## Description

`example` should be set for `url` and `route` independently. 

Note: `route` example won't be dumped until we specify its children.

### CODE REVIEW

File: src/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -752,9 +752,11 @@ private function addWebhookConfigurationNode(string $name): NodeDefinition
             ->children()
                 ->scalarNode('url')
                     ->info('The URL to call.')
+                    ->example('https://webhook.site/#!/view/{some-token}')
                 ->end()
-                ->variableNode('route')
+                ->arrayNode('route')
                     ->info('Route configuration.')
+                    ->example(['my_route', ['param1' => 'value1', 'param2' => 'value2']])
```
Comment (Neirda24) [inline src/DependencyInjection/Configuration.php:759]:
```suggestion
                    ->example([['my_route', ['param1' => 'value1', 'param2' => 'value2']]])
```
I think.

File: src/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -752,9 +752,11 @@ private function addWebhookConfigurationNode(string $name): NodeDefinition
             ->children()
                 ->scalarNode('url')
                     ->info('The URL to call.')
+                    ->example('https://webhook.site/#!/view/{some-token}')
                 ->end()
-                ->variableNode('route')
+                ->arrayNode('route')
```
Comment (Neirda24) [inline src/DependencyInjection/Configuration.php:757]: Why array ? It could be a string as well. Or is there already a normalization process to convert from string to array ?

File: src/DependencyInjection/Configuration.php (hunk 1 above)
Comment (Jean-Beru) [reply src/DependencyInjection/Configuration.php]: Good catch

**Review by Neirda24 — APPROVED** [review]

**Comment by Neirda24** [comment]
thanks @Jean-Beru
